[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install --include=dev",
  "cd server && npm install --include=dev"
]

[phases.build]
cmds = [
  "node node_modules/vite/bin/vite.js build",
  "cd server && node node_modules/typescript/lib/tsc.js"
]

[start]
cmd = "node server/dist/index.js"
