[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install", "cd server && npm install"]

[phases.build]
cmds = ["npx vite build", "cd server && npx tsc"]

[start]
cmd = "node server/dist/index.js"
