CREATE TABLE IF NOT EXISTS company_settings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    company_name VARCHAR(255) NOT NULL,
    logo_path VARCHAR(512) NULL,
    abn VARCHAR(64) NOT NULL,
    address TEXT NULL,
    phone VARCHAR(64) NULL,
    email VARCHAR(255) NULL,
    bsb VARCHAR(32) NOT NULL,
    bank_account_number VARCHAR(64) NOT NULL,
    account_name VARCHAR(255) NULL,
    invoice_prefix VARCHAR(32) NOT NULL DEFAULT 'INV',
    default_due_days INT NOT NULL DEFAULT 7,
    default_currency VARCHAR(16) NOT NULL DEFAULT 'AUD',
    default_line_item_code VARCHAR(64) NOT NULL DEFAULT '09_008_0116_6_3',
    default_line_item_description VARCHAR(255) NOT NULL DEFAULT 'Innovative Community Participation',
    default_hourly_rate DECIMAL(10,2) NOT NULL DEFAULT 50.00,
    rounding_precision INT NOT NULL DEFAULT 2,
    payment_instruction_code VARCHAR(64) NOT NULL DEFAULT 'INV_RR_006_CB',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS invoice_sequences (
    id INT AUTO_INCREMENT PRIMARY KEY,
    invoice_prefix VARCHAR(32) NOT NULL,
    period_key CHAR(6) NOT NULL,
    last_serial INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_invoice_sequence (invoice_prefix, period_key)
);

CREATE TABLE IF NOT EXISTS invoices (
    id INT AUTO_INCREMENT PRIMARY KEY,
    invoice_number VARCHAR(100) NOT NULL,
    user_id INT NULL,
    participant_id INT NULL,
    participant_name VARCHAR(255) NOT NULL,
    participant_ndis_number VARCHAR(64) NOT NULL,
    company_settings_id INT NULL,
    invoice_date DATE NOT NULL,
    due_date DATE NOT NULL,
    date_from DATE NOT NULL,
    date_to DATE NOT NULL,
    status ENUM('draft','unpaid','paid','sent','overdue') NOT NULL DEFAULT 'draft',
    currency VARCHAR(16) NOT NULL DEFAULT 'AUD',
    subtotal DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    total_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    total_hours DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    total_seconds_raw INT NOT NULL DEFAULT 0,
    notes TEXT NULL,
    source_type VARCHAR(64) NOT NULL DEFAULT 'activity_logs',
    created_by_admin_id INT NULL,
    paid_at DATETIME NULL,
    payment_date DATETIME NULL,
    payment_reference VARCHAR(255) NULL,
    pdf_path VARCHAR(512) NULL,
    company_name_snapshot VARCHAR(255) NULL,
    company_abn_snapshot VARCHAR(64) NULL,
    company_address_snapshot TEXT NULL,
    company_phone_snapshot VARCHAR(64) NULL,
    company_email_snapshot VARCHAR(255) NULL,
    company_bsb_snapshot VARCHAR(32) NULL,
    company_bank_account_snapshot VARCHAR(64) NULL,
    company_account_name_snapshot VARCHAR(255) NULL,
    company_logo_snapshot VARCHAR(512) NULL,
    payment_instruction_code VARCHAR(64) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_invoice_number (invoice_number),
    INDEX idx_invoices_status (status),
    INDEX idx_invoices_user (user_id),
    INDEX idx_invoices_date (invoice_date)
);

CREATE TABLE IF NOT EXISTS invoice_items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    invoice_id INT NOT NULL,
    service_date_from DATE NULL,
    service_date_to DATE NULL,
    line_item_code VARCHAR(64) NOT NULL,
    line_item_description VARCHAR(255) NOT NULL,
    quantity_hours DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    rate DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_invoice_items_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE,
    INDEX idx_invoice_items_invoice (invoice_id)
);

CREATE TABLE IF NOT EXISTS invoice_log_sources (
    id INT AUTO_INCREMENT PRIMARY KEY,
    invoice_id INT NOT NULL,
    user_id INT NOT NULL,
    source_start_date DATE NOT NULL,
    source_end_date DATE NOT NULL,
    total_seconds_included INT NOT NULL DEFAULT 0,
    summary_json LONGTEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_invoice_log_sources_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE,
    INDEX idx_invoice_log_sources_invoice (invoice_id),
    INDEX idx_invoice_log_sources_user_date (user_id, source_start_date, source_end_date)
);
